# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - sqlite

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.1

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DB=sqlite

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test


before_script:
  - mkdir -p var/jwt
  - openssl genrsa  -passout pass:"$JWT_PASS" -out var/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:"$JWT_PASS" -pubout -in var/jwt/private.pem -out var/jwt/public.pem
  - php bin/console server:start
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
# Run script
script:
  - vendor/bin/codecept run unit
  - vendor/bin/codecept run acceptance --env phantom
  - vendor/bin/codecept run api

# After a build, send email notification with the build results
notifications:
  email: mieszkomalawski@gmail.com